# Generated by Django 5.0.6 on 2024-06-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nottodo', '0003_rename_end_time_nottodo_scheduled_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nottodo',
            old_name='scheduled_time',
            new_name='scheduled_end_time',
        ),
        migrations.AddField(
            model_name='nottodo',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
