# Generated by Django 5.0.6 on 2024-07-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nottodo', '0005_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
